apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zmbp48ua8-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-0a79da9828.39ei.p3.openshiftapps.com/rhtap/rhtap-qe:51f8b4c0ce301d003b103883d9bcba54fae106fe@sha256:8405c97fd5423eafcc38edfd61809d96c185cc22bd3e1640f2477bc8fdc7e483
          name: container-image
